const TOPICS = [
  {
    id: "family-connections",
    title: "Family Connections",
    cover: "Photo of Coopers",
    image: "images/family connections.webp",
    gallery: [
      "images/family connections.webp",
      "images/familyconnections-images/297 by 297_01.webp",
      "images/familyconnections-images/297 by 297_02.webp",
      "images/familyconnections-images/father and daughter a3.webp",
    ],
    caption: "Generations of local families passed through Vauxhall’s gates, each with their own story. Discover their connections to the factory and to Luton.",
    description: "Family connections were not uncommon throughout the factory at Vauxhall Motors. As one of the town’s largest employers, it attracted generations of workers, many joining straight from school. The company fostered a strong sense of community, actively encouraging employees to recommend relatives for vacancies. At one stage, applicants were even asked to note existing family ties on apprenticeship applications, which were viewed favourably. Long service was common, and in some cases multiple generations of the same family worked at the plant, collectively spanning much of the plants history."
  },
  {
    id: "craftsman-guild",
    title: "Craftsman Guild",
    cover: "Craftsman guild advert",
    image: "images/craftsman guild.webp",
    gallery: [
      "images/craftsman guild.webp",
      "images/vauxhallcraftsmenguild-images/Guild clay hands a2.webp",
      "images/vauxhallcraftsmenguild-images/Guild form 420 by 241.webp",
    ],
    caption: "The Vauxhall Craftsman’s Guild inspired young people to think creatively and become future designers. Explore how it helped shape talent through this competition.",
    description: "Vauxhall Motors worked with local secondary schools to encourage an interest in car design. As one of the region's major employers, it offered a clear pathway into skilled work for young people. Initiatives like the 'Vauxhalls Craftsmans Guild' introduced students to the industry and helped identify talent at an early age. The competition asked participants to design their own Vauxhall car. The models were created using simple materials such as balsa wood and clay, helping participants bring their ideas to life. This hands-on approach gave students a practical introduction to car design and model making. The most promising designs were recognised at special presentation events, and many went on to become designers at Vauxhall."
  },
  {
    id: "migration",
    title: "Migration",
    cover: "Newspaper advert",
    image: "images/Migration.webp",
    gallery: [
      "images/Migration.webp",
      "images/migration-images/A5_01.webp",
      "images/migration-images/A5_02.webp",
      "images/migration-images/Letters a4_01.webp",
      "images/migration-images/Letters a4_02.webp",
      "images/migration-images/migration vocher pargen 145 by 145.webp",
    ],
    caption: "Many people moved to Luton to work at Vauxhall, building new lives for themselves and their families. Learn more about their journeys.",
    description: "Vauxhall played a key role in Luton's growth, providing many new jobs and attracting people from across the UK and overseas, including Ireland, the Caribbean, and South Asia. Although work at the factory was not always the sole reason they moved, it offered the stability, opportunities, and wages that helped them build a better life and ultimately make Luton their home. Work vouchers were introduced under the Commonwealth Immigrations Act of 1962 and were divided into three different categories: A, B and C - depending on individual circumstances.Local migration was also common, with Vauxhall actively recruiting in areas of the UK. Vauxhall regularly visited towns and cities across the UK to recruit new workers, often targeting areas where employment opportunities were limited and offering people a chance to start a new life. It wasn't uncommon to move for work, and durring the late 1950s large industrial firms often supported new employees through this process. even providing hostels for migrant workers while they found permanent accommodation, making the relocation process smooth and straightforward."
  },
  {
    id: "scale",
    title: "Scale",
    cover: "Bus sign",
    image: "images/scale.webp",
    gallery: [
      "images/scale.webp",
      "images/scale-images/1962.webp",
      "images/scale-images/2024.webp",
      "images/scale-images/Large logo a2.webp",
      "images/scale-images/Maps 500 by 500_01.webp",
      "images/scale-images/buses a4.webp",
      "images/scale-images/map overlay 500 by 500 (do not cut off excess).webp",
      "images/scale-images/vauxhall park a4.webp",
    ],
    caption: "As the workforce grew, so did Vauxhall’s presence in Luton. Discover how the factory expanded and shaped the town around it.",
    description: "Around the late 1800's, the New Industries Committee was formed to reduce Luton's reliance on the hat trade and promote the town as a location for emerging businesses. This initiative ultimately led to Vauxhall's relocation to Luton in 1905. As production expanded, so did the plant, with new buildings and factories added over the decades. Vauxhall's presence not only created opportunities for local suppliers and industries, such as AC Delco and Skefco, but the wages of over 30,000 employees supported the local economy, including the many shops and cafes that lined the Kimpton Road. New homes were built, communities grew, and the town's population rose from a few thousand to over 250,000 today.As Vauxhall grew, so did Luton, with new houses built for workers and their families starting a new life in the town. Estates such as the Vauxhall Park Estate were built to accommodate this. Streets like Cavalier Close and Carlton Crescent reflect how the company shaped the town's growth and local identity. Many employees recall rows of buses lining Kimpton Road at finishing time. It could take up to 10 minutes for employees to leave the building they had been working in. To support this management worked with the local bus companies to adjust schedules to match shift times.",
  },
  {
    id: "social-responsibility",
    title: "Social Responsibility",
    cover: "Pay scale booklet",
    image: "images/social responsibility.webp",
    gallery: [
      "images/social responsibility.webp",
      "images/socialresponsibility-images/Childrens trip a4.webp",
      "images/socialresponsibility-images/Clocking in A3.webp",
      "images/socialresponsibility-images/Pentioners newsletter NEW a4.webp",
      "images/socialresponsibility-images/ambulence A3.webp",
      "images/socialresponsibility-images/injured arm a4.webp",
      "images/socialresponsibility-images/modern pentioners a4.webp",
      "images/socialresponsibility-images/pentioners chrismas parcels 297 by 100.webp",
      "images/socialresponsibility-images/pentioners newsletter old a4.webp",
      "images/socialresponsibility-images/physio 297 by 140.webp",
      "images/socialresponsibility-images/suggestion sceme 148 by 148.webp",
      "images/socialresponsibility-images/vauxhall mirror 210 by 275.webp",
    ],
    caption: "Vauxhall supported its workers with benefits beyond the job, from fair pay to an on-site medical centre. Explore its approach to supporting employees.",
    description: "It was often said that Vauxhall was a small town in itself. To support its workforce, the company offered a wide range of perks and benefits, from the Vauxhall Fortnight to health services as well as financial schemes and awards. The Rehabilitation Centre supported employees temporarily unable to perform their usual work due to injury or illness. Light duties allowed them to continue earning a wage while recovering, before returning to their original roles or moving into new positions better suited to their needs. The in-house medical centre treated both minor and major injuries. Medical staff provided round-the-clock care, including physiotherapy and surgery, and even operated an ambulance for serious cases, ensuring employees could receive treatment quickly and safely. The Management Advisory Committee, known as the M.A.C, worked closely with different areas of the factory to listen to employees' concerns and represent their wishes wherever possible. As part of its on-going care, the Vauxhall Pensioners Association continues to create Christmas hampers for members today - a tradition begun by the M.A.C. and featured in this article. Its Welfare Fund also provides support for those facing hardship, ensuring those part of the VPA have access to support in their later years. The Vauxhall Pensioners Association has been active for almost the entirety of Vauxhall's time in Luton, and continues today, despite the factory's closure. Today the VPA is an employee lead organisation, helping former workers stay connected and organises trips far and wide. These connections extended beyond the factory floors, supporting families and former employees for years to come. Each year, Vauxhall treated employees' children to outings at the theatre, circus and ice shows. Here, excited queues wait to board the train with brown bagged lunches full of sandwiches, juice cartons and smarties, ready for the day ahead. Vauxhall was known for paying well, often setting the standard for other local industries in the town. As a result, many spent their working lives at the factory, enjoying a standard of living not typically associated with manual work.",
  },
  {
    id: "apprenticeships",
    title: "Apprenticeships",
    cover: "Apprentice tool",
    image: "images/Apprentiship.webp",
    gallery: [
      "images/Apprentiship.webp",
      "images/apprenticeships-images/Boy with instructor 1 a3.webp",
      "images/apprenticeships-images/Boy with instructor 2 a3.webp",
      "images/apprenticeships-images/Boy with instructor 3 a3.webp",
      "images/apprenticeships-images/girls in classroom 1971 a3.webp",
    ],
    caption: "For many, an apprenticeship at Vauxhall was the start of a long career. See where it led thousands of young people, both inside the factory and beyond.",
    description: "Every year, hundreds of young people joined Vauxhall Motors through its highly sought-after apprenticeship scheme. The two main streams for apprenticeships were craft and commercial, lasting four to five years. Opportunities in areas such as the canteen, photography, and carpentry were also offered, alongside junior roles, graduate schemes, and training for girls, ensuring there was something for every type of learner. / The first year was spent in the training workshop, learning a wide range of skills before moving into specialist departments for practical, hands-on experience. While the scheme helped many people start their careers, it was also highly prestigious and recognised across the industry. In the early days of their training, students made their own toolbox and a range of test pieces, like those shown here. This process helped assess their skills and guided them toward their future specialism in the factory.",
  },
  {
    id: "press-shop",
    title: "Press Shop",
    cover: "Press shop switch",
    image: "images/press shop.webp",
    gallery: [
      "images/press shop.webp",
      "images/pressshop-images/Press shop machines A3.webp",
      "images/pressshop-images/men holding door a3.webp",
      "images/pressshop-images/press in a2.webp",
      "images/pressshop-images/press out a2.webp",
    ],
    caption: "This was where production began, with metal panels pressed into shape. Step inside and see what it was like to work here.",
    description: "The press shop is the first stage in making a car. Large coils of sheet metal, weighing up to 35 tonnes, were unrolled and cut into flat pieces on the blanking line, which could produce 35 parts per minute. Pieces then entered the press line, where dies shaped them into body parts, making anything from floors to doors, and everything in between. The largest press could exert 2,000 tonnes of force on metal less than 1mm thick. Cleanliness was essential as even a single hair caught in the process could leave a mark.",
  },
  {
    id: "body-shop",
    title: "Body Shop",
    cover: "Welding photo",
    image: "images/body shop.webp",
    gallery: [
      "images/body shop.webp",
      "images/bodyshop-images/boys with whelding gun a2.webp",
      "images/bodyshop-images/man with robot a2.webp",
      "images/bodyshop-images/singular whelder a2.webp",
      "images/bodyshop-images/whelding new a2.webp",
      "images/bodyshop-images/women welding a1.webp",
    ],
    caption: "In the Body Shop, panels from the Press Shop were joined to form the car body. Discover how it was done and how the work changed over time.",
    description: "Panels from the press shop and joined together using a combination of welding methods. Hundreds of body shells may pass through this area at once. In modern production, each car required approximately 2200 spot welds and 2.1 metres of weld, carried out using a mix of robotic and manual techniques to ensure quality and consistency. Originally, this work was done entirely by hand. Over 100 individual pressings make up a car body, and precision is critical, to avoid leaks utilising specialist equipment to continuously check component fit to 100th of a millimetre.",
  },
  {
    id: "paint-shop",
    title: "Paint Shop",
    cover: "Colour booklet",
    image: "images/paint shop.webp",
    gallery: [
      "images/paint shop.webp",
      "images/paintshop-images/Robots A2.webp",
      "images/paintshop-images/cleaning a2.webp",
      "images/paintshop-images/control room a2.webp",
      "images/paintshop-images/dunking in pool a2.webp",
      "images/paintshop-images/paint sprayers a2.webp",
      "images/paintshop-images/spray booth colour 220 by 594.webp",
    ],
    caption: "This is where cars were painted and protected, ready for the road ahead. Find out how the process worked and how it changed over time.",
  },
  {
    id: "trim-shop",
    title: "Trim Shop",
    cover: "Sewing machine",
    image: "images/trim shop.webp",
    gallery: [
      "images/trim shop.webp",
      "images/trimshop-images/name badge a2.webp",
      "images/trimshop-images/trim shop lady a1.webp",
      "images/trimshop-images/windscreen a3.webp",
      "images/trimshop-images/wiring man a3.webp",
    ],
    caption: "From carpets to wiring, the trim shop is where vehicles take shape. Find out how each car was completed before heading for its final stages.",
    description: 'As the car leaves the paint shop it rejoined the production line, which stretched thousands of feet around the factory and could hold hundreds of vehicles at once. Furnishing components such as carpets, seats, windows, and wiring, were fitted in the trim shop, using a mix of on-line and off-line processes. In later years, "Just in time" production ensured everything met up before the body moved on to the next area to gain its machinery. It was a busy part of the line, with different teams working simultaneously, gradually turning an empty shell into something much closer to the vehicles we might see on the road today.'
  },
  {
    id: "assembly",
    title: "Assembly",
    cover: "Workwear jumper",
    image: "images/assembly.webp",
    gallery: [
      "images/assembly.webp",
      "images/assembly-images/Hanging cars a0.webp",
      "images/assembly-images/cars on track a2.webp",
      "images/assembly-images/general assembly a3.webp",
      "images/assembly-images/modern photos a4_01.webp",
      "images/assembly-images/modern photos a4_02.webp",
      "images/assembly-images/modern photos a4_03.webp",
      "images/assembly-images/working on car above a3.webp",
    ],
    caption: "This is where the car body meets its mechanical parts, completing the build. Discover how it all came together, here.",
    description: "Here the car body is joined with its mechanical components. Engines, gearboxes, and axles arrive on a conveyor belt from the machining areas, while the body moves down from the trim shop. This final section of the production line stretched 1,000 feet and contained over 60 assembly points, carefully synchronised to the day's production schedule so that each component arrived exactly when needed. Customer orders were converted into coded instructions, guiding workers on any special specifications chosen by the customer. Here, the car first receives its axles, followed by the engine and gearbox, with the wheels fitted last.",
  },
  {
    id: "quality",
    title: "Quality",
    cover: "Quality check photo",
    image: "images/quality.webp",
    gallery: [
      "images/quality.webp",
      "images/quality-images/cans on track a3.webp",
      "images/quality-images/man with panels a2.webp",
    ],
    caption: "The final stage of the production line sees each car carefully inspected to ensure it meets the highest standards. Click here to find out how quality was maintained throughout the assembly process.",
    description: "The Quality control team were responsible for ensuring that every part of a car had been assembled correctly and performed as intended. From paints to plastics, felt to forgings, and carpet to castings, they were involved throughout the entire process, carrying out detailed checks on fit, finish and performance using specialist equipment. No new material entered, and no finished vehicle would exit, without their approval. Their aim was to ensure every Vauxhall meets the high standards expected by its most important inspectors - the customers.",
  },
  {
    id: "toddington",
    title: "Toddington",
    cover: "Parts boxes",
    image: "images/Toddington.webp",
    gallery: [
      "images/Toddington.webp",
      "images/toddington-images/bikes a3.webp",
      "images/toddington-images/lady and shelf a4.webp",
      "images/toddington-images/loading truck a4.webp",
      "images/toddington-images/toddington exterior A1.webp",
    ],
    caption: "Behind the scenes, thousands of parts were picked, packed and dispatched every day. See how the Toddington Road Warehouse kept things moving.",
    description: 'The Toddington Road Warehouse stored spare parts for vehicles, ranging from the smallest nut to complete engines and body panels. Toddington Road Warehouse located in Charlton, Bedfordshire. Opened in 1967, it was on the largest facilities of its kind in the country, employing around 1,000 people and supplying parts to the local factory, dealers, and export markets worldwide. Every day, around 20 tonnes of material left the site, supplying dealers across the UK and overseas. The warehouse was divided into three large sections and held around 20 million parts, each organised by their size and type. Staff rotated through a range of roles; whether it was picking, packing, or restocking items that had run out. Each role was important to ensure the prompt and accurate dispatch of these vital parts. Spanning over 58 acres, the warehouse was vast - large enough to hold 7 Concorde aircrafts. To move around the site efficiently, employees often used bicycles and small trains. In the 1960s rolls of paper and order tickets were used and passed through a network on 2.5 miles of pneumatic tubes carrying invoices and paperwork between departments. Later, these were replaced by handheld digital devices, improving the speed and accuracy of picking and packing. Items of all sizes were handled within the warehouse. Larger parts were loaded directly from storage to flat trucks as part of the "pick-pack" system, ready for distribution across the UK and overseas.'
  },
  {
    id: "other-jobs",
    title: "Other Jobs",
    cover: "ID Badge",
    image: "images/other jobs.webp",
    gallery: [
      "images/other jobs.webp",
      "images/otherjobs-images/chemist a5.webp",
      "images/otherjobs-images/fire fighter a5.webp",
      "images/otherjobs-images/material handling a5.webp",
      "images/otherjobs-images/parts fieldman a5.webp",
      "images/otherjobs-images/printing machines a5.webp",
      "images/otherjobs-images/sam 297 by 297.webp",
      "images/otherjobs-images/service sam 1 A4.webp",
      "images/otherjobs-images/service sam 2 A4.webp",
      "images/otherjobs-images/service sam 3 a4.webp",
      "images/otherjobs-images/service sam 4 a4.webp",
      "images/otherjobs-images/train a5.webp",
    ],
    caption: "There was more to Vauxhall than the production line. Explore the wide range of roles that contributed towards Vauxhall’s success.",
    description: "There were many roles beyond the production line, with a wide range of departments working together to bring cars from initial ideas to the road. From finance to fire services, and chemists to cleaners, thousands of people played a part in shaping every vehicle produced. Material handlers worked across the plant. Here, a worker uses a forklift to move panels from the press shop to the next stage of the production line. They played a vital role in keeping the line moving smoothly and ensuring colleagues had the tools and materials required to do their jobs efficiently. Vauxhall employed a dedicated fire team, pictured here. Operating 24/7 on 4 rotating watches, they provided firefighting, maintenance support and safety training. A central watch tower and grid system allowed fires to be quickly located and tackled, ensuring fast, efficient responses across the factory. The 'Loco' was Vauxhall's own train, used to transport cars and trucks as well as other materials in earlier years. Vehicles were built in the factory, and then broken down into parts and packed into large wooden crates, ready to be shipped across the country and around the world. Everything material and component used in a car was tested by a dedicated team in specialised laboratories. From metals and plastics to fasteners and trimmings, each item was rigorously examined using advanced equipment and testing methods to ensure it met industry standards and performed reliably in every vehicle. The Parts Fieldman was essential in supporting dealers nationwide, ensuring thousands of parts were available. The Service Department handled vehicle issues, while After Sales supplied stock to meet dealers' needs. In a far less connected world, these roles co-ordinated processes that maintained demand and kept the production line running. In 1937, Vauxhall stored 64,000 original drawings of their cars and components in a locked vault, dating back to 1902. These machines could handle master drawing up to 7ft wide and produced 50,000 copies a month. This process continued for decades, supporting the design and engineering of future models as well as other departments. Service Sam, pictured here, was created by commercial artist Haydn Martin, to provide guidance and maintenance support through informative posters. Distributed by the Service Department, examples like those shown to the right were given to dealers to display in workshops and service receptions over the years."
  },
  {
    id: "canteen",
    title: "Canteen",
    cover: "Newspaper clipping",
    image: "images/canteen.webp",
    gallery: [
      "images/canteen.webp",
      "images/canteen-images/Canteen banner 1682 by 1189.webp",
      "images/canteen-images/Canteen full A2.webp",
      "images/canteen-images/Canteen kitchen a4.webp",
      "images/canteen-images/lady serving A3.webp",
      "images/canteen-images/men with tea urn A2.webp",
      "images/canteen-images/viva pudding a4.webp",
    ],
    caption: "The canteen was at the centre of daily life known as a place to eat, meet and socialise. See why so many people remember it so fondly.",
    description: "Due to the size of the workforce and shift patterns, Vauxhall had its own canteen which sat on Kimpton Road. The canteen operated throughout the day and night to serve all shifts. Lunchtime was split into three sittings, ensuring everyone could get a seat and could return promptly to the production line. Breaks were a chance to play cards or dominoes, relax, and catch up with friends. At its peak, more than 25,000 meals were served and over 7,000 cakes and buns were baked daily, all subsidised at a very reasonable price. Plans for a new canteen begun in 1937, and saw many changes over the years, including a two floor expansion. Former employees often recall the large tea urns, like the one pictured here, which came round at break times with milk and sugar already added. Bread and dripping was a daily snack, and queues often formed for a taste of this now lost delicacy. On weekends, the large hall transformed into a social hub for the local community. Activities included roller skating, badminton, and evening dances or performances featuring famous singers of the time, to name a few. Pictured here are hundreds of local scouts children gathering for an event. The canteen team were especially busy at Christmas, when the ever-popular Victor and Viva Puddings, went on sale to employees. These festive treats, similar to a Christmas pudding, were in high demand and in 1965, where over four tonnes were made and sold."
  },
  {
    id: "millbrook",
    title: "Millbrook",
    cover: "Millbrook photo",
    image: "images/millbrook.webp",
    gallery: [
      "images/millbrook.webp",
      "images/millbrook-images/car in water a3.webp",
      "images/millbrook-images/car on bowl a3.webp",
      "images/millbrook-images/crash dummy test A3 .webp",
      "images/millbrook-images/engine testing a2.webp",
      "images/millbrook-images/map 594 by 594.webp",
      "images/millbrook-images/van 45 degrees a2.webp",
    ],
    caption: "Vehicles were put through their paces at the Millbrook Proving Ground. Find out how they were tested before hitting the road.",
  },
  {
    id: "war",
    title: "War",
    cover: "Access pass",
    image: "images/war.webp",
    gallery: [
      "images/war.webp",
      "images/war-images/bomb map a2.webp",
      "images/war-images/churchhill a2.webp",
      "images/war-images/lady working a3.webp",
      "images/war-images/tank a2.webp",
      "images/war-images/van in lake a2.webp",
      "images/war-images/what a soilder said a3.webp",
    ],
    caption: "During the war, Vauxhall played a crucial role in national efforts, producing thousands of tanks and trucks as well as equipment. Learn about life at the factory during these years.",
    description: "When the Second World War began, many Vauxhall workers were called up to serve. Those remaining quickly shifted the factory from car production to military manufacturing. To protect the site from being attacked blackout measures were introduced, which took over 6 weeks to install. On the 30th of August 1940, the factory was bombed by the German Luftwaffe. This map shows the areas of the factory that were damaged. Sadly, 39 employees lost their lives. Repairs were completed in just 5 days, allowing production to resume. Within 89 days, a new engine was designed, built, and tested, and within a year, the first Churchill tank was completed. Winston Churchill and King George VI visited Luton Hoo to observe the tanks being tested, highlighting the significance of the work. By the end of the 6 year conflict, Vauxhall had produced 250,000 Bedford Trucks, 5640 Churchill tanks, and millions of parts and components, making a huge contribution to Britain's war effort. Before the war, women were not employed in the factory due to the physical demands of the work. However, given the urgency, they were welcomed into the workforce, taking on vital roles in assembly, machining and other key operations. Many stayed after the war, marking a major step forward for women in industry. The Vauxhall Mirror continued during the war, publishing letters from former employees serving overseas. These letters often mentioned the parcels sent by the company, including treats to boost morale. Despite the hardships of war, the correspondence shows how strongly the servicemen maintained their connection to colleagues and life back in Luton.",
  },
  {
    id: "bedford-trucks",
    title: "Bedford Trucks",
    cover: "Van badge",
    image: "images/bedford.webp",
    gallery: [
      "images/bedford.webp",
      "images/bedford-trucks-images/first bedford 420 by 420.webp",
      "images/bedford-trucks-images/working on trucks a2.webp",
    ],
    caption: "Known for their exports across the world, Bedford Trucks was once a familiar sight. Explore this important part of Vauxhall’s story.",
    description: "The first Bedford truck was produced in 1931, with 10,000 sold in its first year. By the following year, over 6,000 were already being exported, marking the beginning of a growing global presence. As production expanded, operations moved to Boscombe Road in Dunstable, and by 1973 Bedford Trucks accounted for 37% of British exports in this category. Their versatility made them highly sought after, and they could be seen in countries such as Australia, India and Pakistan. Trucks were fully assembled on site before being carefully dismantled and packed for shipping, ensuring they arrived overseas ready to be rebuilt.",
  },
  {
    id: "mergers",
    title: "Mergers",
    cover: "Ledger cheque",
    image: "images/mergers.webp",
    caption: "Over time, Vauxhall Motors became part of several major partnerships and acquisitions. Take a look how the company evolved through these changes.",
    description: "Vauxhall has undergone a series of partnerships and acquisitions throughout its long history. From its move to Luton and early partnership with General Motors, to the formation of IBC and its eventual acquisition by Stellantis, each stage shaped the company in new ways.",
  },
  {
    id: "unions",
    title: "Unions",
    cover: "Save Vauxhall poster",
    image: "images/unions.webp",
    gallery: [
      "images/unions.webp",
      "images/unions-images/Im backing luton A4.webp",
      "images/unions-images/Last union photo A3_01.webp",
      "images/unions-images/kids protest 210 by 210.webp",
      "images/unions-images/luton worldwide A3.webp",
      "images/unions-images/manor park protest A1.webp",
      "images/unions-images/save vauxhall banner A3.webp",
      "images/unions-images/vauxhall march A3.webp",
    ],
    caption: "Trade unions played a key role in representing workers and shaping workplace life. Discover their influence at Vauxhall by clicking here.",
    description: 'Vauxhall was a closed shop, meaning employees were required to join a union. In its earlier years, the factory experienced few strikes and was often nicknamed "the turnip patch" in the industry. Union representatives, convenors, and shop stewards, all elected by the workforce, worked across the plants to act as a link between employees and management. They helped secure fair pay, improved working conditions and hours, negotiated pensions, and offered support during challenging times such as closures. Manor Park was a short walk away from the Kimpton Road factory. Seen as a neutral place, workers and trade union representatives met here to discuss concerns and vote on key decisions.',
  },
  {
    id: "closure",
    title: "Closure",
    cover: "Closure announcement",
    image: "images/Closure.webp",
    gallery: [
      "images/Closure.webp",
      "images/closure-images/Walking out A2.webp",
      "images/closure-images/a1 outside shot.webp",
      "images/closure-images/cameras a3.webp",
      "images/closure-images/last car a3.webp",
      "images/closure-images/last day a3_01.webp",
      "images/closure-images/last day a3_02.webp",
      "images/closure-images/last day a3_03.webp",
      "images/closure-images/last van off line a2.webp",
      "images/closure-images/on steps a2.webp",
    ],
    audio: "audio/closure.mp3",
    caption: "The factory’s closure marked the end of an era for Luton. Reflect on what it meant for the town and its people.",
    description: "Vauxhall Motors closed its doors for the final time on the 28th March 2025, bringing to an end 120 years of production in Luton. Many will remember the closure of car production in 2002 or the winding down of other local Vauxhall facilities, but this marked the last chapter in a long history. 7,415,045 cars in total were produced in the town in just under 100 years. Alongside sadness, there was a strong sense of pride in what Vauxhall had achieved in the town and the part each worker had played. Many had spent their entire working lives at the plant. Now that Vauxhall's presence in Luton has ended the community has come together and is working to preserve its legacy in the town.",
  },
  {
    id: "community",
    title: "Community",
    cover: "Vauxhall Mirror",
    image: "images/community.webp",
    gallery: [
      "images/community.webp",
      "images/community-images/spectacular a4.webp",
      "images/community-images/classic family fun day A4.webp",
      "images/community-images/sports day a4.webp",
      "images/community-images/sports diary 420 by 186 .webp",
      "images/community-images/skittles a5.webp",
      "images/community-images/griffin players a3.webp",
      "images/community-images/vmvc old a4.webp",
      "images/community-images/vmvc new 297 by 130 .webp",
      "images/community-images/miss luton a4.webp",
      "images/community-images/diversity a5_01.webp",
      "images/community-images/diversity a5_02.webp",
      "images/community-images/diversity a5_03.webp",
      "images/community-images/hearts of gold a3.webp",
      "images/community-images/libary donation a4.webp",
      "images/community-images/balance sheet a4.webp",
    ],
    audio: "audio/community.mp3",
    caption: "Vauxhall was more than a workplace, helping to shape a strong sense of community in Luton and beyond. Explore its lasting impact here.",
    description: "Vauxhall was more than a workplace - it was a hub for community life in Luton. The company created opportunities for workers to connect, share experiences, and enjoy life together through a wide range of activities. From social clubs and sports to special events, and everyday friendships, Vauxhall helped create a sense of belonging and togetherness that extended far beyond the factory walls.  A highlight of the social calendar, the Vauxhall Spectacular was held at the Brache, featuring traditional fair games, performances, and competitions. Many remember the famous faces from television and radio who hosted the event, and the strong sense of community these events created. Many came to work at Vauxhall from across the UK and around the world, bringing with them languages, traditions, and cultures that helped shape Luton into the diverse and vibrant community it is today. The Vauxhall Recreation Club, or the Brache as it was fondly known, was located on Gypsy Lane and was home to hundreds of social clubs covering every hobby. Its impact was so lasting that groups such as the Vauxhall Male Voice Choir and the Griffin Players continue to exist today, as pictured here. Vauxhall played an active role in supporting the local community, making donations that improved everyday life in the town. From funding new technology to creating opportunities for young people, the company ensured its responsibility extended well beyond the factory walls. There were numerous sports teams and clubs connected to Vauxhall, as detailed in the sports diary here. These clubs gave colleagues the opportunity to unwind with friends and enjoy life beyond the factory gates. Support for the community extended beyond the company itself. Vauxhall workers also played their part, fundraising for local charities and supporting good causes.",
  },
  {
    id: "community-art",
    title: "Community Art",
    cover: "Community artwork",
    image: "images/Community Artwork.webp",
    caption: "Vauxhall’s story still inspires people today. Explore artwork created by local people in response to the plant’s history.",
  },
];
