const TOPICS = [
  {
    id: "family-connections",
    title: "Family Connections",
    cover: "Photo of Coopers",
    image: "images/family connections.png",
    caption: "Generations of local families passed through Vauxhall’s gates, each with their own story. Discover their connections to the factory and to Luton.",
  },
  {
    id: "craftsman-guild",
    title: "Craftsman Guild",
    cover: "Craftsman guild advert",
    image: "images/craftsman guild.png",
    caption: "The Vauxhall Craftsman’s Guild inspired young people to think creatively and become future designers. Explore how it helped shape talent through this competition.",
  },
  {
    id: "migration",
    title: "Migration",
    cover: "Newspaper advert",
    image: "images/Migration.png",
    caption: "Many people moved to Luton to work at Vauxhall, building new lives for themselves and their families. Learn more about their journeys.",
  },
  {
    id: "scale",
    title: "Scale",
    cover: "Bus sign",
    image: "images/scale.png",
    caption: "As the workforce grew, so did Vauxhall’s presence in Luton. Discover how the factory expanded and shaped the town around it.",
  },
  {
    id: "social-responsibility",
    title: "Social Responsibility",
    cover: "Pay scale booklet",
    image: "images/social responsibility.png",
    caption: "Vauxhall supported its workers with benefits beyond the job, from fair pay to an on-site medical centre. Explore its approach to supporting employees.",
  },
  {
    id: "apprenticeships",
    title: "Apprenticeships",
    cover: "Apprentice tool",
    image: "images/Apprentiship.png",
    caption: "For many, an apprenticeship at Vauxhall was the start of a long career. See where it led thousands of young people, both inside the factory and beyond.",
  },
  {
    id: "press-shop",
    title: "Press Shop",
    cover: "Press shop switch",
    image: "images/press shop.png",
    caption: "This was where production began, with metal panels pressed into shape. Step inside and see what it was like to work here.",
  },
  {
    id: "body-shop",
    title: "Body Shop",
    cover: "Welding photo",
    image: "images/body shop.png",
    caption: "In the Body Shop, panels from the Press Shop were joined to form the car body. Discover how it was done and how the work changed over time.",
  },
  {
    id: "paint-shop",
    title: "Paint Shop",
    cover: "Colour booklet",
    image: "images/paint shop.png",
    caption: "This is where cars were painted and protected, ready for the road ahead. Find out how the process worked and how it changed over time.",
  },
  {
    id: "trim-shop",
    title: "Trim Shop",
    cover: "Sewing machine",
    image: "images/trim shop.png",
    caption: "From carpets to wiring, the trim shop is where vehicles take shape. Find out how each car was completed before heading for its final stages.",
  },
  {
    id: "assembly",
    title: "Assembly",
    cover: "Workwear jumper",
    image: "images/assembly.png",
    caption: "This is where the car body meets its mechanical parts, completing the build. Discover how it all came together, here.",
  },
  {
    id: "quality",
    title: "Quality",
    cover: "Quality check photo",
    image: "images/quality.png",
    caption: "The final stage of the production line sees each car carefully inspected to ensure it meets the highest standards. Click here to find out how quality was maintained throughout the assembly process.",
  },
  {
    id: "toddington",
    title: "Toddington",
    cover: "Parts boxes",
    image: "images/Toddington.png",
    caption: "Behind the scenes, thousands of parts were picked, packed and dispatched every day. See how the Toddington Road Warehouse kept things moving.",
  },
  {
    id: "other-jobs",
    title: "Other Jobs",
    cover: "ID Badge",
    image: "images/other jobs.png",
    caption: "There was more to Vauxhall than the production line. Explore the wide range of roles that contributed towards Vauxhall’s success.",
  },
  {
    id: "canteen",
    title: "Canteen",
    cover: "Newspaper clipping",
    image: "images/canteen.png",
    caption: "The canteen was at the centre of daily life known as a place to eat, meet and socialise. See why so many people remember it so fondly.",
  },
  {
    id: "millbrook",
    title: "Millbrook",
    cover: "Millbrook photo",
    image: "images/millbrook.png",
    caption: "Vehicles were put through their paces at the Millbrook Proving Ground. Find out how they were tested before hitting the road.",
  },
  {
    id: "war",
    title: "War",
    cover: "Access pass",
    image: "images/war.png",
    caption: "During the war, Vauxhall played a crucial role in national efforts, producing thousands of tanks and trucks as well as equipment. Learn about life at the factory during these years.",
  },
  {
    id: "bedford-trucks",
    title: "Bedford Trucks",
    cover: "Van badge",
    image: "images/bedford.png",
    caption: "Known for their exports across the world, Bedford Trucks was once a familiar sight. Explore this important part of Vauxhall’s story.",
  },
  {
    id: "mergers",
    title: "Mergers",
    cover: "Ledger cheque",
    image: "images/mergers.png",
    caption: "Over time, Vauxhall Motors became part of several major partnerships and acquisitions. Take a look how the company evolved through these changes.",
  },
  {
    id: "unions",
    title: "Unions",
    cover: "Save Vauxhall poster",
    image: "images/unions.png",
    caption: "Trade unions played a key role in representing workers and shaping workplace life. Discover their influence at Vauxhall by clicking here.",
  },
  {
    id: "closure",
    title: "Closure",
    cover: "Closure announcement",
    image: "images/Closure.png",
    caption: "The factory’s closure marked the end of an era for Luton. Reflect on what it meant for the town and its people.",
  },
  {
    id: "community",
    title: "Community",
    cover: "Vauxhall Mirror",
    image: "images/community.png",
    caption: "Vauxhall was more than a workplace, helping to shape a strong sense of community in Luton and beyond. Explore its lasting impact here.",
  },
  {
    id: "community-art",
    title: "Community Art",
    cover: "Community artwork",
    image: "images/Community Artwork.png",
    caption: "Vauxhall’s story still inspires people today. Explore artwork created by local people in response to the plant’s history.",
  },
];
