const TOPICS = [
  { id: 'a', title: 'Family Connections', category: 'Community', description: 'Generations of families working together on the line.', fullContent: 'The factory was more than a workplace; it was a family tradition. Fathers, mothers, sons, and daughters often worked side-by-side. "My dad got me in," was a common phrase heard at the gates. This section explores the deep familial ties that bound the workforce together.', image: 'https://picsum.photos/id/1011/400/300', rotation: 'rotate-2', span: 'col-span-1 md:col-span-2 row-span-1', type: 'photo' },
  { id: 'b', title: 'Craftsman Guild', category: 'Skills', description: 'The dedication to skill and mastery within the plant.', fullContent: "Before automation took over, the craftsman's touch was essential. The Guild represented the pinnacle of manual skill, from pattern making to hand-finished upholstery. We examine the tools and training that defined this era.", image: 'https://picsum.photos/id/250/300/400', rotation: '-rotate-1', span: 'col-span-1 row-span-2', type: 'object' },
  { id: 'c', title: 'Migration', category: 'People', description: 'How the factory drew people from across the globe to Luton.', fullContent: 'Luton changed rapidly in the 20th century, largely driven by the employment opportunities at Vauxhall. Workers arrived from Ireland, the Caribbean, South Asia, and beyond, transforming the cultural fabric of the town.', image: 'https://picsum.photos/id/1025/300/300', rotation: 'rotate-3', span: 'col-span-1 row-span-1', type: 'document' },
  { id: 'd', title: 'Scale', category: 'Production', description: 'The sheer magnitude of operations at the height of production.', fullContent: 'At its peak, the plant produced hundreds of thousands of units per year. This section visualizes the sheer scale of raw materials, energy, and manpower required to keep the lines moving 24/7.', image: 'https://picsum.photos/id/1076/400/300', rotation: '-rotate-2', span: 'col-span-1 md:col-span-2 row-span-1', type: 'photo' },
  { id: 'e', title: 'Social Responsibility', category: 'Ethics', description: "The company's role in the wider Luton community.", fullContent: 'Vauxhall was a major benefactor in Luton, supporting schools, sports clubs, and hospitals. However, the relationship was complex. We look at the interplay between corporate interests and community welfare.', image: 'https://picsum.photos/id/1062/300/300', rotation: 'rotate-1', span: 'col-span-1 row-span-1', type: 'object' },
  { id: 'f', title: 'Apprenticeships', category: 'Training', description: 'Training the next generation of engineers.', fullContent: 'For decades, a Vauxhall apprenticeship was a golden ticket. Young school leavers entered a rigorous program of technical college and on-the-job training, creating a highly skilled workforce that served the region for years.', image: 'https://picsum.photos/id/1059/300/400', rotation: '-rotate-3', span: 'col-span-1 row-span-2', type: 'document' },
  { id: 'g', title: 'Press Shop', category: 'Factory', description: 'The noisy, dangerous heart of car body creation.', fullContent: 'Giant hydraulic presses stamped sheets of steel into doors, roofs, and bonnets. The noise was deafening, the vibration constant. Here, we hear from the men who worked the presses.', image: 'https://picsum.photos/id/1035/300/300', rotation: 'rotate-6', span: 'col-span-1 row-span-1', type: 'photo' },
  { id: 'h', title: 'Paint Shop', category: 'Factory', description: 'Adding color and protection to the steel frames.', fullContent: 'The paint shop was a toxic, colorful environment. From the early days of hand-spraying to the robotic arms of the 90s, the process of sealing and styling the car was critical to its longevity.', image: 'https://picsum.photos/id/104/300/300', rotation: '-rotate-1', span: 'col-span-1 row-span-1', type: 'photo' },
  { id: 'i', title: 'Furnishing Dept', category: 'Interiors', description: 'Stitching, cutting, and fitting the interiors.', fullContent: 'Often employing a large number of women, the furnishing department was where the car became comfortable. Leather, vinyl, and velour were transformed into seats and door cards.', image: 'https://picsum.photos/id/257/300/300', rotation: 'rotate-2', span: 'col-span-1 row-span-1', type: 'object' },
  { id: 'j', title: 'Assembly', category: 'Factory', description: 'Bringing it all together on the main line.', fullContent: 'The assembly line is the iconic image of car production. A synchronized dance of parts and people, where a bare shell became a driving machine in a matter of hours.', image: 'https://picsum.photos/id/146/400/300', rotation: '-rotate-2', span: 'col-span-1 md:col-span-2 row-span-1', type: 'photo' },
  { id: 'k', title: 'Quality', category: 'Standards', description: 'Inspecting the final product before shipping.', fullContent: 'The "ok" stamp. The clipboard check. Quality control was the final gatekeeper. We look at how standards evolved from the post-war boom to the lean manufacturing era.', image: 'https://picsum.photos/id/160/300/300', rotation: 'rotate-1', span: 'col-span-1 row-span-1', type: 'document' },
  { id: 'l', title: 'Toddington Road', category: 'Location', description: 'The impact of the factory on local infrastructure.', fullContent: "The factory didn't just sit in Luton; it reshaped it. Toddington Road became a main artery for logistics, shifting shifts, and the endless stream of transporters leaving the gates.", image: 'https://picsum.photos/id/175/300/300', rotation: '-rotate-1', span: 'col-span-1 row-span-1', type: 'photo' },
  { id: 'm', title: 'Canteen', category: 'Social', description: 'Tea, chips, and conversation during breaks.', fullContent: 'The canteen was the social hub. It was where rumors started, strikes were debated, and friendships were forged over subsidized meals and endless cups of tea.', image: 'https://picsum.photos/id/225/300/300', rotation: 'rotate-3', span: 'col-span-1 row-span-1', type: 'photo' },
  { id: 'n', title: 'Bedford Trucks', category: 'Product', description: 'The heavy duty siblings of the Vauxhall cars.', fullContent: 'While Vauxhall cars were for the family, Bedford trucks built the nation. Produced in the same complex, these workhorses were exported globally and used by the army.', image: 'https://picsum.photos/id/111/300/400', rotation: '-rotate-2', span: 'col-span-1 row-span-2', type: 'object' }
];

const NAV_LINKS = [
  { id: 'gallery', label: 'Gallery' },
  { id: 'process', label: 'Project Process' },
  { id: 'about', label: 'Get Involved' },
  { id: 'contact', label: 'Contact Us' },
];
